# Generated by Django 4.1.5 on 2023-01-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_birthday_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
