# Generated by Django 4.1.5 on 2023-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_purchase_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
